openai:
  default_model: gpt-4o-mini
  models:
    - name: gpt-4o-mini
      max_tokens: 16384
      cost_per_1k_input: 0.00015
      cost_per_1k_output: 0.0006
    - name: gpt-4o
      max_tokens: 128000
      cost_per_1k_input: 0.0025
      cost_per_1k_output: 0.01
    - name: gpt-3.5-turbo
      max_tokens: 16384
      cost_per_1k_input: 0.0005
      cost_per_1k_output: 0.0015

embeddings:
  default_model: text-embedding-3-small
  models:
    - name: text-embedding-3-small
      dimensions: 1536
      cost_per_1k_tokens: 0.00002
    - name: text-embedding-3-large
      dimensions: 3072
      cost_per_1k_tokens: 0.00013

local_models:
  default_model: llama2
  models:
    - name: llama2
      path: models/llama2
      max_tokens: 4096
    - name: mistral
      path: models/mistral
      max_tokens: 8192