# OpenAI model config
openai:
  default_model: gpt-4.1-nano-2025-04-14
  models:
    - name: gpt-4o-mini
      max_tokens: 16384
      cost_per_1k_input: 0.00015
      cost_per_1k_output: 0.0006
    - name: gpt-4o
      max_tokens: 128000
      cost_per_1k_input: 0.0025
      cost_per_1k_output: 0.01
    - name: gpt-4.1-nano-2025-04-14
      max_tokens: 16384
      cost_per_1k_input: 0.0005
      cost_per_1k_output: 0.0015

# Embeddings model config
embeddings:
  default_model: text-embedding-3-small
  models:
    - name: text-embedding-3-small
      dimensions: 1536
      cost_per_1k_tokens: 0.00002
    - name: text-embedding-3-large
      dimensions: 3072
      cost_per_1k_tokens: 0.00013

# Ollama + Local models
local_models:
  default_model: llama3.1:8b
  models:
    - name: llama3.1:8b
      path: models/llama3.1:8b
      max_tokens: 4096